name: Deploy to Azure Container Apps

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
      STORAGE_NAME: ${{ secrets.STORAGE_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Azure 로그인
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR 로그인
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 이미지 빌드 및 푸시
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Container App 배포
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} \
              --container-name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
              --min-replicas 1 \
              --set-env-vars "DB_USER=${{ secrets.DB_USER }}" \
                           "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
                           "DB_HOST=${{ secrets.DB_HOST }}" \
                           "DB_PORT=${{ secrets.DB_PORT }}" \
                           "DB_NAME=${{ secrets.DB_NAME }}" \
                           "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
                           "STORAGE_NAME=${{ secrets.STORAGE_NAME }}" \
                           "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
                           "AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}"
